# Generated by Django 2.2.5 on 2019-09-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='sum',
        ),
        migrations.CreateModel(
            name='Paid_operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Operator')),
                ('paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Paid')),
            ],
        ),
        migrations.AddField(
            model_name='paid',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Borrower'),
        ),
        migrations.CreateModel(
            name='Debt_operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Operator')),
                ('paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Debt')),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Borrower'),
        ),
    ]
